### PR TITLE
Add Color3.fromHSV picker support

### LINKED ISSUE #9: Color3.fromHSV support

### PR DESCRIPTION
**Pull request by JohnnyMorganz**
Adds color picker support for Color3.fromHSV
Closes #9

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Looks good, can you add this to the CHANGELOG?

**Comment by JohnnyMorganz** [comment]
Should be ready now

**Comment by Kampfkarren** [comment]
How does this work with numbers that aren't pretty? I know that's a problem with our Color3.new implementation that I'm not fond of.

**Comment by JohnnyMorganz** [comment]
It currently is the same as the Color3.new situation. There is an issue, however, by attempting to follow the same route as #5 - there isn't really a nice, simple way to convert from RGB to HSV

**Comment by Kampfkarren** [comment]
Doesn't appear to work, is it only with whole numbers?

image

**Comment by JohnnyMorganz** [comment]
> Doesn't appear to work, is it only with whole numbers?
> 
> image

There was actually a missing `.` in the Regex of the last parameter, affecting both Color3.fromHSV and Color3.new
This should be resolved now

**Pull request merged**
